name = "usb_embedded"
description = "Shiny new project"
version = "0.0.0"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <chouteau@adacore.com>"]
maintainers-logins = ["Fabien-Chouteau"]

[[depends-on]]  # This line was added by `alr with`
hal = "~0.1.0"  # This line was added by `alr with`
