pragma Style_Checks (Off);
package USB.Lang is
   Invalid                     : constant Lang_ID := 16#0000#; -- Invalid LANG ID
   Afrikaans                   : constant Lang_ID := 16#0436#; -- Afrikaans
   Albanian                    : constant Lang_ID := 16#041c#; -- Albanian
   Arabic_Saudi_Arabia         : constant Lang_ID := 16#0401#; -- Arabic (Saudi Arabia)
   Arabic_Irak                 : constant Lang_ID := 16#0801#; -- Arabic (Irak)
   Arabic_Egypt                : constant Lang_ID := 16#0c01#; -- Arabic (Egypt)
   Arabic_Lybya                : constant Lang_ID := 16#1001#; -- Arabic (Libya)
   Arabic_Algeria              : constant Lang_ID := 16#1401#; -- Arabic (Algeria)
   Arabic_Morocco              : constant Lang_ID := 16#1801#; -- Arabic (Morocco)
   Arabic_Tunisia              : constant Lang_ID := 16#1c01#; -- Arabic (Tunisia)
   Arabic_Oman                 : constant Lang_ID := 16#2001#; -- Arabic (Oman)
   Arabic_Yemen                : constant Lang_ID := 16#2401#; -- Arabic (Yemen)
   Arabic_Syria                : constant Lang_ID := 16#2801#; -- Arabic (Syria)
   Arabic_Jordan               : constant Lang_ID := 16#2c01#; -- Arabic (Jordan)
   Arabic_Lebanon              : constant Lang_ID := 16#3001#; -- Arabic (Lebanon)
   Arabic_Kuwait               : constant Lang_ID := 16#3401#; -- Arabic (Kuwait)
   Arabic_Uae                  : constant Lang_ID := 16#3801#; -- Arabic (U.A.E.)
   Arabic_Bahrain              : constant Lang_ID := 16#3c01#; -- Arabic (Bahrain)
   Arabic_Qatar                : constant Lang_ID := 16#4001#; -- Arabic (Qatar)
   Armenian                    : constant Lang_ID := 16#042b#; -- Armenian
   Assamese                    : constant Lang_ID := 16#044d#; -- Assamese
   Azeri_Latin                 : constant Lang_ID := 16#042c#; -- Azeri (Latin)
   Azeri_Cyrillic              : constant Lang_ID := 16#082c#; -- Azeri (Cyrillic)
   Basque                      : constant Lang_ID := 16#042d#; -- Basque
   Belarussian                 : constant Lang_ID := 16#0423#; -- Belarussian
   Bengali                     : constant Lang_ID := 16#0445#; -- Bengali
   Bulgarian                   : constant Lang_ID := 16#0402#; -- Bulgarian
   Burmese                     : constant Lang_ID := 16#0455#; -- Burmese
   Catalan                     : constant Lang_ID := 16#0403#; -- Catalan
   Chinese_Taiwan              : constant Lang_ID := 16#0404#; -- Chinese (Taiwan)
   Chinese_Prc                 : constant Lang_ID := 16#0804#; -- Chinese (PRC = People Republic of Chinese)
   Chinese_Hong_Kong           : constant Lang_ID := 16#0c04#; -- Chinese (Hong Kong)
   Chinese_Singapore           : constant Lang_ID := 16#1004#; -- Chinese (Singapore)
   Chinese_Macau_Sar           : constant Lang_ID := 16#1404#; -- Chinese (Macau SAR)
   Croatian                    : constant Lang_ID := 16#041a#; -- Croatian
   Czech                       : constant Lang_ID := 16#0405#; -- Czech
   Danish                      : constant Lang_ID := 16#0406#; -- Danish
   Dutch_Netherlands           : constant Lang_ID := 16#0413#; -- Dutch (Netherlands)
   Dutch_Belgium               : constant Lang_ID := 16#0813#; -- Dutch (Belgium)
   English_United_States       : constant Lang_ID := 16#0409#; -- English (United States)
   English_United_Kingdom      : constant Lang_ID := 16#0809#; -- English (United Kingdom)
   English_Australian          : constant Lang_ID := 16#0c09#; -- English (Australian)
   English_Canadian            : constant Lang_ID := 16#1009#; -- English (Canadian)
   English_New_Zealand         : constant Lang_ID := 16#1409#; -- English (New Zealand)
   English_Ireland             : constant Lang_ID := 16#1809#; -- English (Ireland)
   English_South_Africa        : constant Lang_ID := 16#1c09#; -- English (South Africa)
   English_Jamaica             : constant Lang_ID := 16#2009#; -- English (Jamaica)
   English_Caribbean           : constant Lang_ID := 16#2409#; -- English (Caribbean)
   English_Belize              : constant Lang_ID := 16#2809#; -- English (Belize)
   English_Trinidad            : constant Lang_ID := 16#2c09#; -- English (Trinidad)
   English_Zimbabwe            : constant Lang_ID := 16#3009#; -- English (Zimbabwe)
   English_Phlippines          : constant Lang_ID := 16#3409#; -- English (Philippines)
   Estonian                    : constant Lang_ID := 16#0425#; -- Estonian
   Faeroese                    : constant Lang_ID := 16#0438#; -- Faeroese
   Farsi                       : constant Lang_ID := 16#0429#; -- Farsi
   Finnish                     : constant Lang_ID := 16#040b#; -- Finnish
   French_Standard             : constant Lang_ID := 16#040c#; -- French (Standard)
   French_Belgian              : constant Lang_ID := 16#080c#; -- French (Belgian)
   French_Canadian             : constant Lang_ID := 16#0c0c#; -- French (Canadian)
   French_Switzerland          : constant Lang_ID := 16#100c#; -- French (Switzerland)
   French_Luxembourg           : constant Lang_ID := 16#140c#; -- French (Luxembourg)
   French_Monaco               : constant Lang_ID := 16#180c#; -- French (Monaco)
   Georgian                    : constant Lang_ID := 16#0437#; -- Georgian
   German_Standard             : constant Lang_ID := 16#0407#; -- German (Standard)
   German_Switzerland          : constant Lang_ID := 16#0807#; -- German (Switzerland)
   German_Austria              : constant Lang_ID := 16#0c07#; -- German (Austria)
   German_Luxembourg           : constant Lang_ID := 16#1007#; -- German (Luxembourg)
   German_Liechtenstein        : constant Lang_ID := 16#1407#; -- German (Liechtenstein)
   Greek                       : constant Lang_ID := 16#0408#; -- Greek
   Gujarati                    : constant Lang_ID := 16#0447#; -- Gujarati
   Hebrew                      : constant Lang_ID := 16#040d#; -- Hebrew
   Hindi                       : constant Lang_ID := 16#0439#; -- Hindi
   Hungarian                   : constant Lang_ID := 16#040e#; -- Hungarian
   Icelandic                   : constant Lang_ID := 16#040f#; -- Icelandic
   Indonesian                  : constant Lang_ID := 16#0421#; -- Indonesian
   Italian_Standard            : constant Lang_ID := 16#0410#; -- Italian (Standard)
   Italian_Switzerland         : constant Lang_ID := 16#0810#; -- Italian (Switzerland)
   Japanese                    : constant Lang_ID := 16#0411#; -- Japanese
   Kannada                     : constant Lang_ID := 16#044b#; -- Kannada
   Kashmiri_India              : constant Lang_ID := 16#0860#; -- Kashmiri (India)
   Kazakh                      : constant Lang_ID := 16#043f#; -- Kazakh
   Konkani                     : constant Lang_ID := 16#0457#; -- Konkani
   Korean_Johab                : constant Lang_ID := 16#0412#; -- Korean (Johab)
   Latvian                     : constant Lang_ID := 16#0426#; -- Latvian
   Lithuanian                  : constant Lang_ID := 16#0427#; -- Lithuanian
   Lithuanian_Classic          : constant Lang_ID := 16#0827#; -- Lithuanian (Classic)
   Macedonian                  : constant Lang_ID := 16#042f#; -- Macedonian
   Malay_Malaysian             : constant Lang_ID := 16#043e#; -- Malay (Malaysian)
   Malay_Brunei_Darussalam     : constant Lang_ID := 16#083e#; -- Malay (Brunei Darussalam)
   Malayalam                   : constant Lang_ID := 16#044c#; -- Malayalam
   Manipuri                    : constant Lang_ID := 16#0458#; -- Manipuri
   Marathi                     : constant Lang_ID := 16#044e#; -- Marathi
   Nepali_India                : constant Lang_ID := 16#0861#; -- Nepali (India)
   Norwegian_Bokmal            : constant Lang_ID := 16#0414#; -- Norwegian (Bokmal)
   Norwegian_Nynorsk           : constant Lang_ID := 16#0814#; -- Norwegian (Nynorsk)
   Oriya                       : constant Lang_ID := 16#0448#; -- Oriya
   Polish                      : constant Lang_ID := 16#0415#; -- Polish
   Portuguese_Brazil           : constant Lang_ID := 16#0416#; -- Portuguese (Brazil)
   Portuguese_Standard         : constant Lang_ID := 16#0816#; -- Portuguese (Standard)
   Punjabi                     : constant Lang_ID := 16#0446#; -- Punjabi
   Romanian                    : constant Lang_ID := 16#0418#; -- Romanian
   Russian                     : constant Lang_ID := 16#0419#; -- Russiane
   Sanskrit                    : constant Lang_ID := 16#044f#; -- Sanskrit
   Serbian_Cyrillic            : constant Lang_ID := 16#0c1a#; -- Serbian (Cyrillic)
   Serbian_Latin               : constant Lang_ID := 16#081a#; -- Serbian (Latin)
   Sindhi                      : constant Lang_ID := 16#0459#; -- Sindhi
   Slovak                      : constant Lang_ID := 16#041b#; -- Slovak
   Slovenian                   : constant Lang_ID := 16#0424#; -- Slovenian
   Spannish_Traditional_Sort   : constant Lang_ID := 16#040a#; -- Spannish (Traditional Sort)
   Spannish_Mexican            : constant Lang_ID := 16#080a#; -- Spannish (Mexican)
   Spannish_Modern_Sort        : constant Lang_ID := 16#0c0a#; -- Spannish (Modern Sort)
   Spannish_Guatemala          : constant Lang_ID := 16#100a#; -- Spannish (Guatemala)
   Spannish_Costa_Rica         : constant Lang_ID := 16#140a#; -- Spannish (Costa Rica)
   Spannish_Panama             : constant Lang_ID := 16#180a#; -- Spannish (Panama)
   Spannish_Dominican_Republic : constant Lang_ID := 16#1c0a#; -- Spannish (Dominican Republic)
   Spannish_Venezuela          : constant Lang_ID := 16#200a#; -- Spannish (Venezuela)
   Spannish_Colombia           : constant Lang_ID := 16#240a#; -- Spannish (Colombia)
   Spannish_Peru               : constant Lang_ID := 16#280a#; -- Spannish (Peru)
   Spannish_Argentina          : constant Lang_ID := 16#2c0a#; -- Spannish (Argentina)
   Spannish_Ecuador            : constant Lang_ID := 16#300a#; -- Spannish (Ecuador)
   Spannish_Chile              : constant Lang_ID := 16#340a#; -- Spannish (Chile)
   Spannish_Uruguay            : constant Lang_ID := 16#380a#; -- Spannish (Uruguay)
   Spannish_Paraguay           : constant Lang_ID := 16#3c0a#; -- Spannish (Paraguay)
   Spannish_Bolivia            : constant Lang_ID := 16#400a#; -- Spannish (Bolivia)
   Spannish_El_Salvador        : constant Lang_ID := 16#440a#; -- Spannish (El Salvador)
   Spannish_Honduras           : constant Lang_ID := 16#480a#; -- Spannish (Honduras)
   Spannish_Nicaragua          : constant Lang_ID := 16#4c0a#; -- Spannish (Nicaragua)
   Spannish_Puerto_Rico        : constant Lang_ID := 16#500a#; -- Spannish (Puerto Rico)
   Sutu                        : constant Lang_ID := 16#0430#; -- Sutu
   Swahili_Kenya               : constant Lang_ID := 16#0441#; -- Swahili (Kenya)
   Swedish                     : constant Lang_ID := 16#041d#; -- Swedish
   Swedish_Finland             : constant Lang_ID := 16#081d#; -- Swedish (Finland)
   Tamil                       : constant Lang_ID := 16#0449#; -- Tamil
   Tatar_Tatarstan             : constant Lang_ID := 16#0444#; -- Tatar (Tatarstan)
   Telugu                      : constant Lang_ID := 16#044a#; -- Telugu
   Thai                        : constant Lang_ID := 16#041e#; -- Thai
   Turkish                     : constant Lang_ID := 16#041f#; -- Turkish
   Ukrainian                   : constant Lang_ID := 16#0422#; -- Ukrainian
   Urdu_Pakistan               : constant Lang_ID := 16#0420#; -- Urdu (Pakistan)
   Urdu_India                  : constant Lang_ID := 16#0820#; -- Urdu (India)
   Uzbek_Latin                 : constant Lang_ID := 16#0443#; -- Uzbek (Latin)
   Uzbek_Cyrillic              : constant Lang_ID := 16#0843#; -- Uzbek (Cyrillic)
   Vietnamese                  : constant Lang_ID := 16#042a#; -- Vietnamese
   Hid_Udd                     : constant Lang_ID := 16#04ff#; -- HID (Usage Data Descriptor)
   Hid1                        : constant Lang_ID := 16#f0ff#; -- HID (Vendor Defined 1)
   Hid2                        : constant Lang_ID := 16#f4ff#; -- HID (Vendor Defined 2)
   Hid3                        : constant Lang_ID := 16#f8ff#; -- HID (Vendor Defined 3)
   Hid4                        : constant Lang_ID := 16#fcff#; -- HID (Vendor Defined 4)
end USB.Lang;
